/* Server-side committee orchestration.

   When ANTHROPIC_API_KEY is set, the six-agent debate is generated by Claude
   (claude-opus-4-8) as one structured-output call grounded in the live quote,
   then streamed to the client line-by-line for the "live committee" feel.

   When the key is absent or the call fails, we fall back to the deterministic
   engine in committee.ts — so the product works end-to-end today and goes live
   the moment the key is added. Same Debate shape either way. */

import Anthropic from "@anthropic-ai/sdk";
import {
  buildDebate,
  AGENTS,
  type Debate,
  type DebateLine,
  type AgentScore,
  type Decision,
  type AgentId,
  type Phase,
} from "./committee";
import { fetchRobinhoodQuotes } from "./quotes";
import { stopLoss, takeProfit } from "./paperTrading";
import { getQuote } from "./market";

const MODEL = "claude-opus-4-8";

const AGENT_IDS: AgentId[] = ["marcus", "diana", "raymond", "priya", "solomon", "chair"];
const PHASES: Phase[] = ["convene", "opening", "cross", "synthesis", "verdict"];

const SYSTEM = `You are the AICOS Investment Committee — six specialist agents that debate a single equity before any capital is deployed. Reproduce a rigorous institutional committee meeting: independent analysis, genuine cross-examination, evidence, and a final ruling.

The agents:
- marcus — The Bull. Aggressive, high-conviction. Finds asymmetric upside, growth, catalysts.
- diana — The Bear. Relentlessly skeptical. Valuation, competitive threats, fraud/quality red flags, downside scenarios.
- raymond — The Quant. No narrative, only mathematics: factor loads, volatility, Sharpe, drawdown, expected return.
- priya — Macro Strategist. Always zoomed out: rates, inflation, liquidity, regime, sector rotation.
- solomon — Chief Risk Officer. Protects capital: position sizing, concentration, liquidity, tail risk, kill conditions.
- chair — Final decision-maker. No bias. Weighs all desks, resolves conflict, issues the ruling.

Produce a committee transcript and a final decision. Rules:
- Open with the chair convening (phase "convene"), then one opening statement per specialist (phase "opening").
- Then a cross-examination (phase "cross") where agents directly challenge or concede to each other — set "rebuts" to the agent being addressed.
- A short chair synthesis (phase "synthesis"), then the chair's ruling (phase "verdict", kind "ruling").
- 12-16 lines total. Each line's "text" is 1-3 sentences, in that agent's voice. Be specific and quantitative; cite the live price where relevant. Do not invent precise financials you cannot know — frame as analysis, ranges, and scenarios.
- Scores: one per specialist (not the chair). score 0-100. signal in buy/sell/hold/reduce/avoid. 2-3 terse evidence bullets each.
- Solomon MUST state a specific stop PRICE — an actual dollar level, not a percentage — reasoned from the nearest technical support, the name's volatility, and the catalyst timeline. Put that exact level in decision.stop.
- The Chair MUST set a specific take-profit PRICE derived from the bull-case price target, discounted by the confidence score (lower confidence → pull the target in). Put that exact level in decision.priceTarget.
- decision.stop and decision.priceTarget are the levels the paper engine will use, so they must be the committee's genuinely reasoned levels for THIS setup — not a fixed percentage off entry.
- Decision verdict in BUY/WATCHLIST/SPECULATIVE/REDUCE/SELL, with confidence 0-100, max allocation %, a 2-4 sentence thesis synthesizing the debate, and 2-3 kill conditions.
The verdict must follow from the debate — if Diana and Solomon win the room, do not rule BUY.`;

const SCHEMA = {
  type: "object",
  additionalProperties: false,
  properties: {
    lines: {
      type: "array",
      items: {
        type: "object",
        additionalProperties: false,
        properties: {
          agent: { type: "string", enum: AGENT_IDS },
          phase: { type: "string", enum: PHASES },
          kind: {
            type: "string",
            enum: ["statement", "challenge", "concession", "evidence", "ruling"],
          },
          rebuts: { anyOf: [{ type: "string", enum: AGENT_IDS }, { type: "null" }] },
          text: { type: "string" },
        },
        required: ["agent", "phase", "kind", "rebuts", "text"],
      },
    },
    scores: {
      type: "array",
      items: {
        type: "object",
        additionalProperties: false,
        properties: {
          agent: { type: "string", enum: ["marcus", "diana", "raymond", "priya", "solomon"] },
          score: { type: "integer" },
          label: { type: "string" },
          signal: { type: "string", enum: ["buy", "sell", "hold", "reduce", "avoid"] },
          bullets: { type: "array", items: { type: "string" } },
        },
        required: ["agent", "score", "label", "signal", "bullets"],
      },
    },
    decision: {
      type: "object",
      additionalProperties: false,
      properties: {
        verdict: { type: "string", enum: ["BUY", "WATCHLIST", "SPECULATIVE", "REDUCE", "SELL"] },
        confidence: { type: "integer" },
        priceTarget: { type: "number" },
        stop: { type: "number" },
        maxAllocationPct: { type: "number" },
        thesis: { type: "string" },
        killConditions: { type: "array", items: { type: "string" } },
      },
      required: [
        "verdict",
        "confidence",
        "priceTarget",
        "stop",
        "maxAllocationPct",
        "thesis",
        "killConditions",
      ],
    },
  },
  required: ["lines", "scores", "decision"],
} as const;

export interface LiveDebate extends Debate {
  live: boolean;
}

export async function generateDebate(rawTicker: string): Promise<LiveDebate> {
  const ticker = rawTicker.toUpperCase().trim() || "NVDA";

  if (!process.env.ANTHROPIC_API_KEY) {
    return { ...buildDebate(ticker), live: false };
  }

  const quote = (await fetchRobinhoodQuotes([ticker])).get(ticker) ?? getQuote(ticker);
  const company = quote.name;

  try {
    const client = new Anthropic();
    const response = await client.messages.create({
      model: MODEL,
      max_tokens: 16000,
      thinking: { type: "adaptive" },
      system: SYSTEM,
      output_config: {
        format: { type: "json_schema", schema: SCHEMA },
      },
      messages: [
        {
          role: "user",
          content: `Convene the committee on ${ticker} (${company}). Live price $${quote.last.toFixed(
            2,
          )}, ${quote.changePct >= 0 ? "+" : ""}${quote.changePct.toFixed(
            2,
          )}% on the day, prior close $${quote.prevClose.toFixed(
            2,
          )}. Run the full meeting and issue a ruling.`,
        },
      ],
    });

    const text = response.content
      .filter((b): b is Anthropic.TextBlock => b.type === "text")
      .map((b) => b.text)
      .join("");

    const parsed = JSON.parse(text) as {
      lines: Omit<DebateLine, "id">[];
      scores: AgentScore[];
      decision: Decision;
    };

    const lines: DebateLine[] = parsed.lines.map((l, i) => ({
      ...l,
      rebuts: l.rebuts ?? undefined,
      id: `${ticker}-${i}`,
    }));

    // The committee's own reasoned levels take precedence. Fall back to the
    // canonical formula defaults only when the model omits a level.
    const valid = (v: unknown): v is number =>
      typeof v === "number" && Number.isFinite(v) && v > 0;
    let stop = parsed.decision.stop;
    let priceTarget = parsed.decision.priceTarget;
    if (!valid(stop)) {
      console.warn(`[committee] ${ticker}: no stop from committee — using formula default`);
      stop = stopLoss(quote.last);
    }
    if (!valid(priceTarget)) {
      console.warn(`[committee] ${ticker}: no target from committee — using formula default`);
      priceTarget = takeProfit(quote.last);
    }
    const decision: Decision = { ...parsed.decision, ticker, company, stop, priceTarget };

    // keep scorecard in committee roster order
    const order = AGENTS.map((a) => a.id);
    const scores = [...parsed.scores].sort(
      (a, b) => order.indexOf(a.agent) - order.indexOf(b.agent),
    );

    return { ticker, company, lines, scores, decision, live: true };
  } catch (err) {
    console.error("[committee] live generation failed, using fallback:", err);
    return { ...buildDebate(ticker), live: false };
  }
}
